# ----------------------------------------------------------------
# WHAT IS THIS FILE FOR?
# https://nsustain.com = Flarum
# https://BeeMovr.nsustain.com = BeeMovr
# https://GoodLifeFarms.nsustain.com = Good Life Farms
# ----------------------------------------------------------------

# We use Compose Version 3.3 because it's the recommended version
# by Kompose, which automatically converts Compose files into
# Kubernetes objects.
# Source:
#   https://kompose.io/conversion/#version-table
version: "3.3"
services:
  flarum:
    image: nsustain/flarum:latest
    container_name: flarum
    # Always restart the container, even after reboot
    restart: unless-stopped
    pull_policy: never
    build:
      context: ./nsustain.com/src/docker
      dockerfile: flarum.Dockerfile
    depends_on:
      - mariadb
      - nginx
    expose:
      - 9000  # used by PHP-FPM
    networks:
      - back-end
    volumes:
      # These are the data files for the container.
      # Location of these files:
      #   /var/lib/docker/volumes/...
      - flarum-data:/var/www/html/flarum
    env_file:
     - ./nsustain.com/src/docker/.env_flarum

  beemovr:
    container_name: beemovr
    build:
      context: ./BeeMovr
      dockerfile: Dockerfile.beemovr
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - back-end
    expose:
      - 3000  # used by Node (pnpm)

  goodlifefarms:
    container_name: goodlifefarms
    build:
      context: ./GoodLifeFarms
      dockerfile: Dockerfile.goodlifefarms
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - back-end
    expose:
      - 3000  # used by Node (pnpm)

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - cloudflared
    restart: unless-stopped
    pull_policy: always
    ports:
      - 80:80
      - 443:443
    networks:
      - back-end
    volumes:
      - flarum-data:/var/www/html/flarum
      - ./configs_nginx/nginx.conf:/etc/nginx/nginx.conf

      # When you first run our image, these volumes will
      # be empty. However, if you'd like to set up https / SSL,
      # these volumes will be used for storing the certificates.
      - letsencrypt-data:/etc/letsencrypt

      # certbot uses lock-files system for its internal functions.
      # Source:
      #   https://eff-certbot.readthedocs.io/en/stable/using.html#where-certs
      - letsencrypt-lockfiles:/var/lib/letsencrypt
    command:
      - nginx
      - -g
      - daemon off;

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    pull_policy: always
    expose:
      - 3306  # used by MariaDB
    networks:
      - back-end
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
     - ./nsustain.com/src/docker/.env_mariadb

volumes:
  flarum-data:
    external: true
    name: flarum-data
  letsencrypt-data:
    external: true
    name: letsencrypt-data
  letsencrypt-lockfiles:
    external: true
    name: letsencrypt-lockfiles
  mariadb-data:
    external: true
    name: mariadb-data

# "The presence of these objects is sufficient to define them"
# Source:
#   https://docs.docker.com/compose/compose-file/
networks:
  back-end: {}
