#!/usr/bin/env bash

sudo tarsnap -c --print-stats --humanize-numbers \
  -f "$(uname -n)-$(date +%Y-%m-%d_%H-%M-%S)" \
  /var/lib/docker/volumes/ \
  /home/soobinrho/deploy-nsustain.com/**/.env* 2>&1 | \
    xargs logger --id --priority user.info -t tarsnap

if [ $? -eq 0 ]; then
	logger --id --priority user.info -t tarsnap "Tarsnap backup success."
else
	logger --id --priority user.err -t tarsnap "Tarsnap backup error."
fi
