#!/usr/bin/env bash

find . -type f -name ".env*" | \
  xargs sudo tarsnap -c \
  --print-stats \
  --humanize-numbers \
  -f "$(uname -n)-$(date +%Y-%m-%d_%H-%M-%S)" \
  --exclude *.example \
  /var/lib/docker/volumes/ 2>&1 | \
    logger --id --priority user.info -t tarsnap

if [ $? -eq 0 ]; then
	logger --id --priority user.info -t tarsnap "Tarsnap backup success."
else
	logger --id --priority user.err -t tarsnap "Tarsnap backup error."
fi
